version : "3"
services :
  docker-mysql:
    image:
      mysql:latest
    ports:
    - 3307:3306
    env_file:
      - ./.env
    volumes:
    - mysql-data:/var/lib/mysql
  burger-builder-api :
    image: burger-builder-api
    ports:
    - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - docker-mysql
volumes:
  mysql-data:
    driver: local